// Mocks generated by Mockito 5.4.6 from annotations
// in scam_message_detector/test/support/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:connectivity_plus/connectivity_plus.dart' as _i16;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i17;
import 'package:flutter_llama/flutter_llama.dart' as _i7;
import 'package:flutter_llama/src/models/generation_params.dart' as _i10;
import 'package:flutter_llama/src/models/llama_config.dart' as _i9;
import 'package:flutter_llama/src/models/llama_response.dart' as _i2;
import 'package:flutter_llama/src/models/model_source.dart' as _i11;
import 'package:flutter_llama/src/models/preset_model.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:scam_message_detector/features/scam_detector/data/datasources/gemini_remote_datasource.dart'
    as _i21;
import 'package:scam_message_detector/features/scam_detector/data/datasources/groq_remote_datasource.dart'
    as _i20;
import 'package:scam_message_detector/features/scam_detector/data/dtos/scam_analysis_dto.dart'
    as _i3;
import 'package:scam_message_detector/features/scam_detector/data/services/connectivity_service.dart'
    as _i18;
import 'package:scam_message_detector/features/scam_detector/data/services/llama_native_probe.dart'
    as _i15;
import 'package:scam_message_detector/features/scam_detector/data/services/local_scam_analysis_service.dart'
    as _i27;
import 'package:scam_message_detector/features/scam_detector/data/services/model_download_service.dart'
    as _i13;
import 'package:scam_message_detector/features/scam_detector/domain/entities/scam_analysis.dart'
    as _i4;
import 'package:scam_message_detector/features/scam_detector/domain/entities/threat_intel_snapshot.dart'
    as _i5;
import 'package:scam_message_detector/features/scam_detector/domain/repositories/abuse_ipdb_repository.dart'
    as _i24;
import 'package:scam_message_detector/features/scam_detector/domain/repositories/connectivity_repository.dart'
    as _i19;
import 'package:scam_message_detector/features/scam_detector/domain/repositories/eml_parse_repository.dart'
    as _i6;
import 'package:scam_message_detector/features/scam_detector/domain/repositories/local_analysis_repository.dart'
    as _i28;
import 'package:scam_message_detector/features/scam_detector/domain/repositories/model_repository.dart'
    as _i29;
import 'package:scam_message_detector/features/scam_detector/domain/repositories/pii_redaction_repository.dart'
    as _i26;
import 'package:scam_message_detector/features/scam_detector/domain/repositories/scam_analysis_repository.dart'
    as _i22;
import 'package:scam_message_detector/features/scam_detector/domain/repositories/url_scan_repository.dart'
    as _i25;
import 'package:scam_message_detector/features/scam_detector/domain/repositories/virus_total_repository.dart'
    as _i23;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLlamaResponse_0 extends _i1.SmartFake implements _i2.LlamaResponse {
  _FakeLlamaResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScamAnalysisDto_1 extends _i1.SmartFake
    implements _i3.ScamAnalysisDto {
  _FakeScamAnalysisDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScamAnalysis_2 extends _i1.SmartFake implements _i4.ScamAnalysis {
  _FakeScamAnalysis_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVirusTotalResult_3 extends _i1.SmartFake
    implements _i5.VirusTotalResult {
  _FakeVirusTotalResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAbuseIpdbResult_4 extends _i1.SmartFake
    implements _i5.AbuseIpdbResult {
  _FakeAbuseIpdbResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUrlScanResult_5 extends _i1.SmartFake implements _i5.UrlScanResult {
  _FakeUrlScanResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeParsedEmlContent_6 extends _i1.SmartFake
    implements _i6.ParsedEmlContent {
  _FakeParsedEmlContent_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FlutterLlama].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLlama extends _i1.Mock implements _i7.FlutterLlama {
  @override
  bool get isModelLoaded =>
      (super.noSuchMethod(
            Invocation.getter(#isModelLoaded),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<bool> loadModel(_i9.LlamaConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#loadModel, [config]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i2.LlamaResponse> generate(_i10.GenerationParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#generate, [params]),
            returnValue: _i8.Future<_i2.LlamaResponse>.value(
              _FakeLlamaResponse_0(
                this,
                Invocation.method(#generate, [params]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.LlamaResponse>.value(
              _FakeLlamaResponse_0(
                this,
                Invocation.method(#generate, [params]),
              ),
            ),
          )
          as _i8.Future<_i2.LlamaResponse>);

  @override
  _i8.Stream<String> generateStream(_i10.GenerationParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#generateStream, [params]),
            returnValue: _i8.Stream<String>.empty(),
            returnValueForMissingStub: _i8.Stream<String>.empty(),
          )
          as _i8.Stream<String>);

  @override
  _i8.Future<void> unloadModel() =>
      (super.noSuchMethod(
            Invocation.method(#unloadModel, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>?> getModelInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getModelInfo, []),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<void> stopGeneration() =>
      (super.noSuchMethod(
            Invocation.method(#stopGeneration, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> loadModelWithAutoDownload({
    required String? modelId,
    _i11.ModelSource? source = _i11.ModelSource.huggingFace,
    String? variant,
    String? specificFile,
    _i9.LlamaConfig? config,
    required _i11.DownloadProgressCallback? onProgress,
    bool? autoDownload = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadModelWithAutoDownload, [], {
              #modelId: modelId,
              #source: source,
              #variant: variant,
              #specificFile: specificFile,
              #config: config,
              #onProgress: onProgress,
              #autoDownload: autoDownload,
            }),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> loadPresetModel({
    required _i12.PresetModel? preset,
    _i9.LlamaConfig? config,
    required _i11.DownloadProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadPresetModel, [], {
              #preset: preset,
              #config: config,
              #onProgress: onProgress,
            }),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [ModelDownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockModelDownloadService extends _i1.Mock
    implements _i13.ModelDownloadService {
  @override
  _i8.Future<void> downloadModelInBackground() =>
      (super.noSuchMethod(
            Invocation.method(#downloadModelInBackground, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isModelDownloaded() =>
      (super.noSuchMethod(
            Invocation.method(#isModelDownloaded, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<String> getModelPath() =>
      (super.noSuchMethod(
            Invocation.method(#getModelPath, []),
            returnValue: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#getModelPath, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#getModelPath, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> downloadModel({
    required void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadModel, [], {#onProgress: onProgress}),
            returnValue: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#downloadModel, [], {
                  #onProgress: onProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#downloadModel, [], {
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> deleteModel() =>
      (super.noSuchMethod(
            Invocation.method(#deleteModel, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [LlamaNativeProbe].
///
/// See the documentation for Mockito's code generation for more information.
class MockLlamaNativeProbe extends _i1.Mock implements _i15.LlamaNativeProbe {
  @override
  _i8.Future<bool> isAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void invalidate() => super.noSuchMethod(
    Invocation.method(#invalidate, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i16.Connectivity {
  @override
  _i8.Stream<List<_i17.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i8.Stream<List<_i17.ConnectivityResult>>.empty(),
            returnValueForMissingStub:
                _i8.Stream<List<_i17.ConnectivityResult>>.empty(),
          )
          as _i8.Stream<List<_i17.ConnectivityResult>>);

  @override
  _i8.Future<List<_i17.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i8.Future<List<_i17.ConnectivityResult>>.value(
              <_i17.ConnectivityResult>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i17.ConnectivityResult>>.value(
                  <_i17.ConnectivityResult>[],
                ),
          )
          as _i8.Future<List<_i17.ConnectivityResult>>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i18.ConnectivityService {
  @override
  _i8.Future<bool> isOnline() =>
      (super.noSuchMethod(
            Invocation.method(#isOnline, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [ConnectivityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityRepository extends _i1.Mock
    implements _i19.ConnectivityRepository {
  @override
  _i8.Future<bool> isOnline() =>
      (super.noSuchMethod(
            Invocation.method(#isOnline, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [GroqRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroqRemoteDataSource extends _i1.Mock
    implements _i20.GroqRemoteDataSource {
  @override
  bool get isConfigured =>
      (super.noSuchMethod(
            Invocation.getter(#isConfigured),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<_i3.ScamAnalysisDto> analyzeAugmentedContent(
    String? masterPrompt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeAugmentedContent, [masterPrompt]),
            returnValue: _i8.Future<_i3.ScamAnalysisDto>.value(
              _FakeScamAnalysisDto_1(
                this,
                Invocation.method(#analyzeAugmentedContent, [masterPrompt]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.ScamAnalysisDto>.value(
              _FakeScamAnalysisDto_1(
                this,
                Invocation.method(#analyzeAugmentedContent, [masterPrompt]),
              ),
            ),
          )
          as _i8.Future<_i3.ScamAnalysisDto>);

  @override
  _i8.Future<_i3.ScamAnalysisDto> analyzeMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeMessage, [message]),
            returnValue: _i8.Future<_i3.ScamAnalysisDto>.value(
              _FakeScamAnalysisDto_1(
                this,
                Invocation.method(#analyzeMessage, [message]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.ScamAnalysisDto>.value(
              _FakeScamAnalysisDto_1(
                this,
                Invocation.method(#analyzeMessage, [message]),
              ),
            ),
          )
          as _i8.Future<_i3.ScamAnalysisDto>);
}

/// A class which mocks [GeminiRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiRemoteDataSource extends _i1.Mock
    implements _i21.GeminiRemoteDataSource {
  @override
  _i8.Future<_i3.ScamAnalysisDto> analyzeMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeMessage, [message]),
            returnValue: _i8.Future<_i3.ScamAnalysisDto>.value(
              _FakeScamAnalysisDto_1(
                this,
                Invocation.method(#analyzeMessage, [message]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.ScamAnalysisDto>.value(
              _FakeScamAnalysisDto_1(
                this,
                Invocation.method(#analyzeMessage, [message]),
              ),
            ),
          )
          as _i8.Future<_i3.ScamAnalysisDto>);

  @override
  _i8.Future<_i3.ScamAnalysisDto> analyzeAugmentedContent(
    String? masterPrompt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeAugmentedContent, [masterPrompt]),
            returnValue: _i8.Future<_i3.ScamAnalysisDto>.value(
              _FakeScamAnalysisDto_1(
                this,
                Invocation.method(#analyzeAugmentedContent, [masterPrompt]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.ScamAnalysisDto>.value(
              _FakeScamAnalysisDto_1(
                this,
                Invocation.method(#analyzeAugmentedContent, [masterPrompt]),
              ),
            ),
          )
          as _i8.Future<_i3.ScamAnalysisDto>);
}

/// A class which mocks [ScamAnalysisRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScamAnalysisRepository extends _i1.Mock
    implements _i22.ScamAnalysisRepository {
  @override
  _i8.Future<_i4.ScamAnalysis> analyzeMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeMessage, [message]),
            returnValue: _i8.Future<_i4.ScamAnalysis>.value(
              _FakeScamAnalysis_2(
                this,
                Invocation.method(#analyzeMessage, [message]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.ScamAnalysis>.value(
              _FakeScamAnalysis_2(
                this,
                Invocation.method(#analyzeMessage, [message]),
              ),
            ),
          )
          as _i8.Future<_i4.ScamAnalysis>);

  @override
  _i8.Future<_i4.ScamAnalysis> analyzeAugmentedPrompt(String? masterPrompt) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeAugmentedPrompt, [masterPrompt]),
            returnValue: _i8.Future<_i4.ScamAnalysis>.value(
              _FakeScamAnalysis_2(
                this,
                Invocation.method(#analyzeAugmentedPrompt, [masterPrompt]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.ScamAnalysis>.value(
              _FakeScamAnalysis_2(
                this,
                Invocation.method(#analyzeAugmentedPrompt, [masterPrompt]),
              ),
            ),
          )
          as _i8.Future<_i4.ScamAnalysis>);
}

/// A class which mocks [VirusTotalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVirusTotalRepository extends _i1.Mock
    implements _i23.VirusTotalRepository {
  @override
  _i8.Future<_i5.VirusTotalResult> scanUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#scanUrl, [url]),
            returnValue: _i8.Future<_i5.VirusTotalResult>.value(
              _FakeVirusTotalResult_3(this, Invocation.method(#scanUrl, [url])),
            ),
            returnValueForMissingStub: _i8.Future<_i5.VirusTotalResult>.value(
              _FakeVirusTotalResult_3(this, Invocation.method(#scanUrl, [url])),
            ),
          )
          as _i8.Future<_i5.VirusTotalResult>);
}

/// A class which mocks [AbuseIpdbRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbuseIpdbRepository extends _i1.Mock
    implements _i24.AbuseIpdbRepository {
  @override
  _i8.Future<_i5.AbuseIpdbResult> checkIp(String? ipAddress) =>
      (super.noSuchMethod(
            Invocation.method(#checkIp, [ipAddress]),
            returnValue: _i8.Future<_i5.AbuseIpdbResult>.value(
              _FakeAbuseIpdbResult_4(
                this,
                Invocation.method(#checkIp, [ipAddress]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.AbuseIpdbResult>.value(
              _FakeAbuseIpdbResult_4(
                this,
                Invocation.method(#checkIp, [ipAddress]),
              ),
            ),
          )
          as _i8.Future<_i5.AbuseIpdbResult>);
}

/// A class which mocks [UrlScanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUrlScanRepository extends _i1.Mock implements _i25.UrlScanRepository {
  @override
  _i8.Future<_i5.UrlScanResult> submitUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#submitUrl, [url]),
            returnValue: _i8.Future<_i5.UrlScanResult>.value(
              _FakeUrlScanResult_5(this, Invocation.method(#submitUrl, [url])),
            ),
            returnValueForMissingStub: _i8.Future<_i5.UrlScanResult>.value(
              _FakeUrlScanResult_5(this, Invocation.method(#submitUrl, [url])),
            ),
          )
          as _i8.Future<_i5.UrlScanResult>);
}

/// A class which mocks [EmlParseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmlParseRepository extends _i1.Mock
    implements _i6.EmlParseRepository {
  @override
  _i6.ParsedEmlContent parse(String? rawEml) =>
      (super.noSuchMethod(
            Invocation.method(#parse, [rawEml]),
            returnValue: _FakeParsedEmlContent_6(
              this,
              Invocation.method(#parse, [rawEml]),
            ),
            returnValueForMissingStub: _FakeParsedEmlContent_6(
              this,
              Invocation.method(#parse, [rawEml]),
            ),
          )
          as _i6.ParsedEmlContent);
}

/// A class which mocks [PiiRedactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPiiRedactionRepository extends _i1.Mock
    implements _i26.PiiRedactionRepository {
  @override
  _i8.Future<String> scrubPii(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#scrubPii, [input]),
            returnValue: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#scrubPii, [input]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#scrubPii, [input]),
              ),
            ),
          )
          as _i8.Future<String>);
}

/// A class which mocks [LocalScamAnalysisService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalScamAnalysisService extends _i1.Mock
    implements _i27.LocalScamAnalysisService {
  @override
  _i8.Future<bool> isUsable() =>
      (super.noSuchMethod(
            Invocation.method(#isUsable, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i4.ScamAnalysis> analyze(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#analyze, [message]),
            returnValue: _i8.Future<_i4.ScamAnalysis>.value(
              _FakeScamAnalysis_2(this, Invocation.method(#analyze, [message])),
            ),
            returnValueForMissingStub: _i8.Future<_i4.ScamAnalysis>.value(
              _FakeScamAnalysis_2(this, Invocation.method(#analyze, [message])),
            ),
          )
          as _i8.Future<_i4.ScamAnalysis>);

  @override
  _i4.ScamAnalysis parseModelResponseForTest(String? raw) =>
      (super.noSuchMethod(
            Invocation.method(#parseModelResponseForTest, [raw]),
            returnValue: _FakeScamAnalysis_2(
              this,
              Invocation.method(#parseModelResponseForTest, [raw]),
            ),
            returnValueForMissingStub: _FakeScamAnalysis_2(
              this,
              Invocation.method(#parseModelResponseForTest, [raw]),
            ),
          )
          as _i4.ScamAnalysis);
}

/// A class which mocks [LocalAnalysisRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalAnalysisRepository extends _i1.Mock
    implements _i28.LocalAnalysisRepository {
  @override
  _i8.Future<_i4.ScamAnalysis> analyze(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#analyze, [message]),
            returnValue: _i8.Future<_i4.ScamAnalysis>.value(
              _FakeScamAnalysis_2(this, Invocation.method(#analyze, [message])),
            ),
            returnValueForMissingStub: _i8.Future<_i4.ScamAnalysis>.value(
              _FakeScamAnalysis_2(this, Invocation.method(#analyze, [message])),
            ),
          )
          as _i8.Future<_i4.ScamAnalysis>);
}

/// A class which mocks [ModelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockModelRepository extends _i1.Mock implements _i29.ModelRepository {
  @override
  _i8.Future<bool> isModelDownloaded() =>
      (super.noSuchMethod(
            Invocation.method(#isModelDownloaded, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}
